### ISSUE TITLE
Can't open files with .pd extension outside the app

### ISSUE THREAD

**Issue by fomalsd** [danomatika/PdParty#69]
Now this could be an iOS 13 beta bug, so please correct me if I'm wrong, but:
I wasn't able to open app from .pd files, there is no such option despite format being called "Pure Data Patch" on second screenshot.
![i](https://user-images.githubusercontent.com/10403536/62982959-790e4300-be36-11e9-805c-4c07fd83e659.jpg)
![i](https://user-images.githubusercontent.com/10403536/62982957-790e4300-be36-11e9-8ff7-1ea1d1d9bb64.PNG)
Reproduced it with both 1.2.1 AppStore and self-compiled version, tested using iPadOS 13.0 beta 5 (17A5547d)
Can anyone confirm/deny that?

**Comment by danomatika** [comment]
This should be fixed with the latest commits. Basically, this wasn't being handled when the open request was sent to PdParty.

**Comment by danomatika** [comment]
Sharing via AirDrop is working with the current master for the upcoming 1.3.0 release.

**Comment by thumpclang** [comment]
I see that this fix is ready to go for the next PdParty release, but I’d like to quickly note my observation that this issue has been the #1 obstacle for non-tech-savvy users to be willing to try out the app. My students (musicians, not programmers) are generally fine with installing PdParty & trying to open a Pd file from AirDrop, Messages, Mail, Files, etc., but when I send detailed instructions for WebDAV or other means of transferring a patch, ~80% of them give up & will no longer try. As I mentioned in my [comment](https://github.com/danomatika/PdParty/issues/84#issuecomment-1000002699) on issue #84, please sign me up for any testing I could do that might help facilitate the next release!

**Comment by Despair-Bear** [comment]
Was this issue ever resolved?  I still can't seem to be able open downloaded pd patches on my iPad

**Comment by danomatika** [comment]
Should be fixed in 1.3.0 beta which is in testing.

—-

For those that wish to join in testing, install the free TestFlight app on your iDevice, then open this TestFlight link:

https://testflight.apple.com/join/17ZZ5AC7

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com
